### ISSUE TITLE
Ayuda con la práctica: Interacción HTML

### ISSUE THREAD

**Issue by EEGS2425** [EEGS2425/practica_dwec_gestor_presupuesto#1]
@pedroprieto

**Buenos días Pedro. Necesito tu ayuda, "he acabado" la práctica de interacción HTML, pero justo cuando llega a la parte en la que tiene que crear los objetos con la función CrearGasto, justo en este primer objeto:**

let gasto1 = gestionPresupuesto.CrearGasto("Compra carne", 23.44, "2021-10-06", "casa", "comida"); 

**se detiene y me lanza el siguiente error:**

**Uncaught TypeError: Cannot add property fecha, object is not extensible.**

Cuando sigo el programa con la depuración, veo que dentro de CrearGasto, se para en la primera línea:   

this.fecha = Date.parse(new Date());

y me lanza el error. Por probar, he puesto esta línea un poquito más abajo, y me lanza exactamente el mismo error, pero esta vez con la descripción:

this.descripcion = descripcion;

Seguramente, tendré infinidad de errores en el código,  pero este no entiendo lo que me quiere decir. Gracias por tu atención.

**Comment by pedroprieto** [comment]
Buenas,

Esta línea es incorrecta:
```js
let gasto1 = gestionPresupuesto.CrearGasto("Compra carne", 23.44, "2021-10-06", "casa", "comida");
```

Es una función constructora: tienes que crear los gastos con `new`:
```js
let gasto1 = new gestionPresupuesto.CrearGasto("Compra carne", 23.44, "2021-10-06", "casa", "comida");
```
Un saludo!!
